### ISSUE TITLE
Great Progress!

### ISSUE THREAD

**Issue by DansDesigns** [Pippadi/combadge#1]
Hi Pippadi, 

Loving the progress youve made!
I see you have moved over to the new ESP32 chips.. have you tested the built-in speech recognition functions yet?

Have you considered putting a video together showing the current working state or the Badge?

Keep up the good work!

**Comment by Pippadi** [comment]
Thank you!

No, not yet! I was under the impression earlier that I needed a separate DSP chip or something for the speech recognition to work, but some more reading tells me that I don't. Thanks for the reminder!

College and stuff has been keeping me busy lately, so I haven't been able to give this project as much attention as I want to. I'm trying to get some kind of real-time multi-badge audio streaming working with a central bridge. Perhaps that should be my milestone for the first video.

I've been meaning to learn a little bit about audio signal processing, so that I can implement some basic echo and noise cancellation. Again, I haven't found the time, and these don't look like the kind of topics that can be covered in a week or two :)

**Comment by Pippadi** [comment]
Enabled the Discussions feature. Closing.
