### ISSUE TITLE
Feature Request: Touch Sensor Input(s)

### ISSUE THREAD

**Issue by cinderblock** [Pippadi/combadge#2]
Awesome work!

I see that the ESP32-S3 has a Touch controller. Have you considered bringing a couple GPIO out that have touch support? Could make for awesome touch buttons!

**Comment by Pippadi** [comment]
Thank you!
The current iteration of the hardware does in fact have three touch-capable GPIOs broken out (see [schematic](https://github.com/Pippadi/combadge/blob/main/hardware/pcb/assets/TopLevelSchematic.png)).

`TCH1` is intended to be connected to the chevron and act as the main button. `TCH2` and `TCH3` were admittedly added as afterthoughts, and are just broken out to some test points because I was out of board space :)

At present, the software makes use of only `TCH1`, but I'm sure some use will be found for the other two.

**Comment by cinderblock** [comment]
Oh dam! I didn't see a schematic print so I couldn't investigate fully without starting up the full KiCad and was going off of, what may be old, renderings.

Carry on :)
